### ISSUE TITLE
:setup overwrites existing template folder

### ISSUE THREAD

**Issue by patrickstorm** [visormatt/generator-react-up#5]
# Overview:
Found this out the hard way.

If the template folder exists (default _templates), running setup and specifying that folder overwrites the folder completely. Just noting it here for later, its not a critical issue.

**Comment by visormatt** [comment]
https://github.com/visormatt/generator-react-up/pull/6

**Comment by visormatt** [comment]
Closing this out with PR https://github.com/visormatt/generator-react-up/pull/6
